# Generated by Django 5.2.7 on 2025-11-04 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("image", models.ImageField(upload_to="uploads/categories/")),
                ("base_price", models.FloatField(default=0.0)),
                ("max_amount_of_lettering_items", models.IntegerField(default=-1)),
                ("height", models.FloatField(default=0.0)),
                ("width", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_email", models.CharField(max_length=256)),
                ("image", models.ImageField(upload_to="uploads/comments/")),
                ("text", models.TextField(blank=True)),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LetteringItemCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("price", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "lettering item categories",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_email", models.CharField(max_length=256)),
                ("amount", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "color_in_hex",
                    models.CharField(
                        default="#000000",
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}){1,2}$", "only valid hex color code is accepted"
                            )
                        ],
                    ),
                ),
                ("color_nickname", models.CharField(default="add nickname", max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("image", models.ImageField(blank=True, upload_to="uploads/products/")),
                ("detail_image", models.ImageField(blank=True, upload_to="uploads/products_detail")),
                ("is_uploaded", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tsa_products.category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="tsa_products.product"
                    ),
                ),
                (
                    "product_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tsa_products.productcolor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordered_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("user_email", models.CharField(max_length=256)),
                ("user_first_name", models.CharField(blank=True, max_length=256)),
                ("user_last_name", models.CharField(blank=True, max_length=256)),
                ("address1", models.CharField(default="Address line 1", max_length=1024)),
                ("address2", models.CharField(blank=True, default="Address line 2", max_length=1024, null=True)),
                ("ordered", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tsa_products.payment"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tsa_products.productvariation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LetteringItemVariation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lettering", models.CharField(max_length=256)),
                (
                    "lettering_item_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tsa_products.letteringitemcategory",
                    ),
                ),
                (
                    "product_variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lettering_item_variation_set",
                        to="tsa_products.productvariation",
                    ),
                ),
            ],
        ),
    ]
